name: staging-Backend
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  Approval:
    runs-on: ubuntu-latest
    steps:
      - name: Approval
        uses: trstringer/manual-approval@v1
        timeout-minutes: 5
        with:
          minimum-approvals: 1
          secret: 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
          approvers: remintroy

  Build_And_Copy_files_to_EC2:
    runs-on: ubuntu-latest
    needs: Approval
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - run: pwd
      - run: npm i --force
      - run: npm run build
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass
      - name: "Copying Files"
        run: sshpass -p "erp1234" scp -o StrictHostKeyChecking=accept-new  /home/runner/work/feeOn-backend/feeOn-backend/dist/index.js ubuntu@65.2.123.21:/home/ubuntu/feeon_backend/
      - name: SSH to server and restarting PM2
        run: sshpass -p "erp1234" ssh ubuntu@65.2.123.21 "pm2 restart backend"
