name: staging-Backend
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  Approval:
    runs-on: ubuntu-latest
    steps:
      - name: Approval
        uses: trstringer/manual-approval@v1
        timeout-minutes: 5
        with:
          minimum-approvals: 1
          secret: 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
          approvers: remintroy

  Build_And_Copy_files_to_EC2:
    runs-on: ubuntu-latest
    needs: Approval
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - run: pwd
      - run: npm i --force
      - run: npm run build
      - name: "Copying Files"
        uses: garygrossgarten/github-action-scp@release
        with:
          local: /home/runner/work/feeOn-backend/feeOn-backend/dist
          remote: /home/ubuntu/feeon_backend/
          host: 65.2.123.21
          username: ubuntu
          password: erp1234
