name: Backend
on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main
jobs:
  SonarCloudSCan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
              -Dsonar.organization=rekhugopal
              -Dsonar.projectKey=SonarCloudCodeAnalyisi


  build_and_delploy:
    runs-on: ubuntu-latest
    needs: SonarCloudSCan
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - run: pwd
      - run: npm i --force
      - run: npm run build
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass
      - name: "Copying Files"
        run: sshpass -p "1421@Ffan" scp -o StrictHostKeyChecking=accept-new  /home/runner/work/feeontestback/feeontestback/dist/index.js ubuntu@54.224.100.175:/home/ubuntu/feeon_backend/
      - name: SSH to server and restarting PM2
        run: sshpass -p "1421@Ffan" ssh ubuntu@54.224.100.175  "pm2 restart backend"
